# Assignment - PY/02

- Lambda Functions

In [1]:
import pandas as pd
from pydataset import data

# Load mtcars dataset
df = data('mtcars')

In [2]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## 4.1 Add Two Columns
- Create a new column `mpg_hp_sum` = mpg + hp using a lambda function.

In [3]:
df['mpg_hp_sum'] = df.apply(lambda row: row['mpg'] + row['hp'], axis=1)
df[['mpg', 'hp', 'mpg_hp_sum']].head()

                    mpg   hp  mpg_hp_sum
Mazda RX4          21.0  110       131.0
Mazda RX4 Wag      21.0  110       131.0
Datsun 710         22.8   93       115.8
Hornet 4 Drive     21.4  110       131.4
Hornet Sportabout  18.7  175       193.7

## 4.2 Conditional Label
- Create a new column `mpg_label`:
  - "High" if mpg > 20
  - "Low" otherwise
- Use `apply()` with a lambda.

In [4]:
df['mpg_label'] = df['mpg'].apply(lambda x: "High" if x > 20 else "Low")
df[['mpg', 'mpg_label']].head()

                    mpg mpg_label
Mazda RX4          21.0      High
Mazda RX4 Wag      21.0      High
Datsun 710         22.8      High
Hornet 4 Drive     21.4      High
Hornet Sportabout  18.7       Low

## 4.3 Multiply Column Values
- Double all `hp` values using `map()` with a lambda.

*Note: to avoid overwriting `hp` (which later tasks such as 4.7 and 4.10 rely on), the doubled values are stored in a new column `hp_doubled` rather than replacing `hp` in place.*

In [5]:
df['hp_doubled'] = df['hp'].map(lambda x: x * 2)
df[['hp', 'hp_doubled']].head()

                    hp  hp_doubled
Mazda RX4          110         220
Mazda RX4 Wag      110         220
Datsun 710          93         186
Hornet 4 Drive     110         220
Hornet Sportabout  175         350

## 4.4 Filter Rows
- Get a list of all `mpg` values greater than 25 using `filter()` with a lambda.

In [6]:
mpg_gt_25 = list(filter(lambda x: x > 25, df['mpg']))
print(mpg_gt_25)

[32.4, 30.4, 33.9, 27.3, 26.0, 30.4]

## 4.5 Reduce to Total
- Use `reduce()` with a lambda to sum all `cyl` values in the dataset.

In [7]:
from functools import reduce

total_cyl = reduce(lambda a, b: a + b, df['cyl'])
print("Total cylinders across all cars:", total_cyl)

Total cylinders across all cars: 198

## 4.6 Sort by Custom Rule
- Sort the dataset by the reverse of the car names' length using `sorted()` with a lambda on the index.

In [8]:
sorted_names = sorted(df.index, key=lambda name: -len(name))
df_sorted_by_name_len = df.loc[sorted_names]
df_sorted_by_name_len.head(10)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_doubled
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,225.4,Low,430
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,215.4,Low,410
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,350
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,244.7,Low,460
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,165.5,Low,300
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,194.2,Low,350
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High,220
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,98.9,High,130
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,279.8,Low,528
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High,220

## 4.7 Multi-Column Condition
- Create a column `efficient_power` = "Yes" if mpg > 20 and hp > 100, else "No".

In [9]:
df['efficient_power'] = df.apply(lambda row: "Yes" if (row['mpg'] > 20 and row['hp'] > 100) else "No", axis=1)
df[['mpg', 'hp', 'efficient_power']].head(10)

                    mpg   hp efficient_power
Mazda RX4          21.0  110             Yes
Mazda RX4 Wag      21.0  110             Yes
Datsun 710         22.8   93              No
Hornet 4 Drive     21.4  110             Yes
Hornet Sportabout  18.7  175              No
Valiant            18.1  105              No
Duster 360         14.3  245              No
Merc 240D          24.4   62              No
Merc 230           22.8   95              No
Merc 280           19.2  123              No

## 4.8 Normalize a Column
- Normalize `mpg` between 0 and 1 using a lambda inside `apply()`:
- normalized = (x - min) / (max - min)

In [10]:
mpg_min = df['mpg'].min()
mpg_max = df['mpg'].max()

df['mpg_normalized'] = df['mpg'].apply(lambda x: (x - mpg_min) / (mpg_max - mpg_min))
df[['mpg', 'mpg_normalized']].head(10)

                    mpg  mpg_normalized
Mazda RX4          21.0        0.451064
Mazda RX4 Wag      21.0        0.451064
Datsun 710         22.8        0.527660
Hornet 4 Drive     21.4        0.468085
Hornet Sportabout  18.7        0.353191
Valiant            18.1        0.327660
Duster 360         14.3        0.165957
Merc 240D          24.4        0.595745
Merc 230           22.8        0.527660
Merc 280           19.2        0.374468

## 4.9 Extract First Word
- Extract the first word from each car name (index) into a new column `car_make` using `map()` with a lambda.

In [11]:
df['car_make'] = df.index.map(lambda name: name.split()[0])
df[['car_make']].head(10)

                  car_make
Mazda RX4            Mazda
Mazda RX4 Wag        Mazda
Datsun 710          Datsun
Hornet 4 Drive      Hornet
Hornet Sportabout   Hornet
Valiant            Valiant
Duster 360          Duster
Merc 240D             Merc
Merc 230              Merc
Merc 280              Merc

## 4.10 Square and Add
- Create a column `hp_mpg_calc` = (hp² + mpg²) using `apply()` with a lambda.

In [12]:
df['hp_mpg_calc'] = df.apply(lambda row: row['hp'] ** 2 + row['mpg'] ** 2, axis=1)
df[['hp', 'mpg', 'hp_mpg_calc']].head(10)

                    hp   mpg  hp_mpg_calc
Mazda RX4          110  21.0     12541.00
Mazda RX4 Wag      110  21.0     12541.00
Datsun 710          93  22.8      9168.84
Hornet 4 Drive     110  21.4     12557.96
Hornet Sportabout  175  18.7     30974.69
Valiant            105  18.1     11352.61
Duster 360         245  14.3     60229.49
Merc 240D           62  24.4      4439.36
Merc 230            95  22.8      9544.84
Merc 280           123  19.2     15497.64

## 4.11 Filter by Col values
- Filter cars with mpg > 25.

In [13]:
mpg_over_25 = df[df['mpg'] > 25]
mpg_over_25[['mpg', 'hp']]

                 mpg   hp
Fiat 128        32.4   66
Honda Civic     30.4   52
Toyota Corolla  33.9   65
Fiat X1-9       27.3   66
Porsche 914-2   26.0   91
Lotus Europa    30.4  113

## 4.12 Filter and sorted car names by horsepower
- From above, return a list of car names sorted by horsepower.

In [14]:
car_names_sorted_by_hp = mpg_over_25.sort_values('hp').index.tolist()
print(car_names_sorted_by_hp)

['Honda Civic', 'Toyota Corolla', 'Fiat 128', 'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa']