# MySQL Assignment : SQL/01
## EMP-DEPT table

In [1]:
# SQL - PYTHON Connect
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [2]:
# Connect to the piit MySQL database (root user, password Mysql@123 per assignment instructions)
engine1 = create_engine("mysql+pymysql://root:Mysql%40123@localhost/piit")

# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [3]:
# Load base tables
emp = q("SELECT * FROM emp")
emp['hiredate'] = pd.to_datetime(emp['hiredate'])
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     15 non-null     int64
 1   ename     15 non-null     str
 2   job       15 non-null     str
 3   mgr       14 non-null     float64
 4   hiredate  15 non-null     datetime64[s]
 5   sal       15 non-null     float64
 6   comm      5 non-null      float64
 7   deptno    15 non-null     int64
dtypes: datetime64[s](1), float64(3), int64(2), str(2)
memory usage: 1.1 KB

In [4]:
dept = q("SELECT * FROM dept")
dept

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [5]:
emp

    empno   ename        job     mgr   hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0 1988-12-17  5000.0   100.0      10
1    7369   SMITH      CLERK  7902.0 1980-12-17   800.0     NaN      20
2    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
3    7521    WARD   SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
4    7566   JONES    MANAGER  7839.0 1981-04-02  2975.0     NaN      20
5    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
6    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850.0     NaN      30
7    7782   CLARK    MANAGER  7839.0 1981-06-09  2450.0     NaN      10
8    7788   SCOTT    ANALYST  7566.0 1987-04-19  3000.0     NaN      20
9    7839    KING  PRESIDENT     NaN 1981-11-17  5000.0     NaN      10
10   7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0 1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0 1981-12-03   950.0     NaN      30
13   7902    FORD    ANALYST  7566.0 1981-12-03  3000.0     NaN      20
14   7934  MILLER      CLERK  7782.0 1982-01-23  1300.0     NaN      10

---
## Write the queries for the following

### 1. List the names of analysts and salesmen.

In [6]:
# MYSQL Query
q("""SELECT ename, job FROM emp WHERE job IN ('ANALYST','SALESMAN')""")

    ename       job
0  DHIRAJ   ANALYST
1   ALLEN  SALESMAN
2    WARD  SALESMAN
3  MARTIN  SALESMAN
4   SCOTT   ANALYST
5  TURNER  SALESMAN
6    FORD   ANALYST

In [7]:
# Equivalent pandas code
result = emp[emp['job'].isin(['ANALYST', 'SALESMAN'])][['ename', 'job']]
result

     ename       job
0   DHIRAJ   ANALYST
2    ALLEN  SALESMAN
3     WARD  SALESMAN
5   MARTIN  SALESMAN
8    SCOTT   ANALYST
10  TURNER  SALESMAN
13    FORD   ANALYST

### 2. List details of employees who have joined before 30 Sep 81.

In [8]:
# MYSQL Query
q("""SELECT * FROM emp WHERE hiredate < '1981-09-30'""")

   empno   ename       job   mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800.0     NaN      20
1   7499   ALLEN  SALESMAN  7698  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698  1981-02-22  1250.0   500.0      30
3   7566   JONES   MANAGER  7839  1981-04-02  2975.0     NaN      20
4   7654  MARTIN  SALESMAN  7698  1981-09-28  1250.0  1400.0      30
5   7698   BLAKE   MANAGER  7839  1981-05-01  2850.0     NaN      30
6   7782   CLARK   MANAGER  7839  1981-06-09  2450.0     NaN      10
7   7844  TURNER  SALESMAN  7698  1981-09-08  1500.0     0.0      30

In [9]:
# Equivalent pandas code
result = emp[emp['hiredate'] < '1981-09-30']
result

    empno   ename       job     mgr   hiredate     sal    comm  deptno
1    7369   SMITH     CLERK  7902.0 1980-12-17   800.0     NaN      20
2    7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
3    7521    WARD  SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
4    7566   JONES   MANAGER  7839.0 1981-04-02  2975.0     NaN      20
5    7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
6    7698   BLAKE   MANAGER  7839.0 1981-05-01  2850.0     NaN      30
7    7782   CLARK   MANAGER  7839.0 1981-06-09  2450.0     NaN      10
10   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500.0     0.0      30

### 3. List names of employees who are not managers.

In [10]:
# MYSQL Query
q("""SELECT ename, job FROM emp WHERE job <> 'MANAGER'""")

     ename        job
0   DHIRAJ    ANALYST
1    SMITH      CLERK
2    ALLEN   SALESMAN
3     WARD   SALESMAN
4   MARTIN   SALESMAN
5    SCOTT    ANALYST
6     KING  PRESIDENT
7   TURNER   SALESMAN
8    ADAMS      CLERK
9    JAMES      CLERK
10    FORD    ANALYST
11  MILLER      CLERK

In [11]:
# Equivalent pandas code
result = emp[emp['job'] != 'MANAGER'][['ename', 'job']]
result

     ename        job
0   DHIRAJ    ANALYST
1    SMITH      CLERK
2    ALLEN   SALESMAN
3     WARD   SALESMAN
5   MARTIN   SALESMAN
8    SCOTT    ANALYST
9     KING  PRESIDENT
10  TURNER   SALESMAN
11   ADAMS      CLERK
12   JAMES      CLERK
13    FORD    ANALYST
14  MILLER      CLERK

### 4. List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.

In [12]:
# MYSQL Query
q("""SELECT empno, ename FROM emp WHERE empno IN (7369, 7521, 7839, 7934, 7788)""")

   empno   ename
0   7369   SMITH
1   7521    WARD
2   7788   SCOTT
3   7839    KING
4   7934  MILLER

In [13]:
# Equivalent pandas code
result = emp[emp['empno'].isin([7369, 7521, 7839, 7934, 7788])][['empno', 'ename']]
result

    empno   ename
1    7369   SMITH
3    7521    WARD
8    7788   SCOTT
9    7839    KING
14   7934  MILLER

### 5. List employees not belonging to department 30, 40, or 10.

In [14]:
# MYSQL Query
q("""SELECT * FROM emp WHERE deptno NOT IN (30, 40, 10)""")

   empno  ename      job   mgr    hiredate     sal  comm  deptno
0   7369  SMITH    CLERK  7902  1980-12-17   800.0  None      20
1   7566  JONES  MANAGER  7839  1981-04-02  2975.0  None      20
2   7788  SCOTT  ANALYST  7566  1987-04-19  3000.0  None      20
3   7876  ADAMS    CLERK  7788  1987-05-23  1100.0  None      20
4   7902   FORD  ANALYST  7566  1981-12-03  3000.0  None      20

In [15]:
# Equivalent pandas code
result = emp[~emp['deptno'].isin([30, 40, 10])]
result

    empno  ename      job     mgr   hiredate     sal  comm  deptno
1    7369  SMITH    CLERK  7902.0 1980-12-17   800.0   NaN      20
4    7566  JONES  MANAGER  7839.0 1981-04-02  2975.0   NaN      20
8    7788  SCOTT  ANALYST  7566.0 1987-04-19  3000.0   NaN      20
11   7876  ADAMS    CLERK  7788.0 1987-05-23  1100.0   NaN      20
13   7902   FORD  ANALYST  7566.0 1981-12-03  3000.0   NaN      20

### 6. List employee names for those who have joined between 30 June and 31 Dec '81.

In [16]:
# MYSQL Query
q("""SELECT ename, hiredate FROM emp WHERE hiredate BETWEEN '1981-06-30' AND '1981-12-31'""")

    ename    hiredate
0  MARTIN  1981-09-28
1    KING  1981-11-17
2  TURNER  1981-09-08
3   JAMES  1981-12-03
4    FORD  1981-12-03

In [17]:
# Equivalent pandas code
result = emp[(emp['hiredate'] >= '1981-06-30') & (emp['hiredate'] <= '1981-12-31')][['ename', 'hiredate']]
result

     ename   hiredate
5   MARTIN 1981-09-28
9     KING 1981-11-17
10  TURNER 1981-09-08
12   JAMES 1981-12-03
13    FORD 1981-12-03

### 7. List the different designations in the company.

In [18]:
# MYSQL Query
q("""SELECT DISTINCT job FROM emp""")

         job
0    ANALYST
1      CLERK
2   SALESMAN
3    MANAGER
4  PRESIDENT

In [19]:
# Equivalent pandas code
result = pd.DataFrame({'job': emp['job'].unique()})
result

         job
0    ANALYST
1      CLERK
2   SALESMAN
3    MANAGER
4  PRESIDENT

### 8. List the names of employees who are not eligible for commission.

In [20]:
# MYSQL Query
q("""SELECT ename FROM emp WHERE comm IS NULL""")

    ename
0   SMITH
1   JONES
2   BLAKE
3   CLARK
4   SCOTT
5    KING
6   ADAMS
7   JAMES
8    FORD
9  MILLER

In [21]:
# Equivalent pandas code
result = emp[emp['comm'].isna()][['ename']]
result

     ename
1    SMITH
4    JONES
6    BLAKE
7    CLARK
8    SCOTT
9     KING
11   ADAMS
12   JAMES
13    FORD
14  MILLER

### 9. List the name and designation of the employee who does not report to anybody.

In [22]:
# MYSQL Query
q("""SELECT ename, job FROM emp WHERE mgr IS NULL""")

  ename        job
0  KING  PRESIDENT

In [23]:
# Equivalent pandas code
result = emp[emp['mgr'].isna()][['ename', 'job']]
result

  ename        job
9  KING  PRESIDENT

### 10. List the employees not assigned to any department.

In [24]:
# MYSQL Query
q("""SELECT * FROM emp WHERE deptno IS NULL""")

Empty DataFrame
Columns: [empno, ename, job, mgr, hiredate, sal, comm, deptno]
Index: []

In [25]:
# Equivalent pandas code
result = emp[emp['deptno'].isna()]
result

Empty DataFrame
Columns: [empno, ename, job, mgr, hiredate, sal, comm, deptno]
Index: []

### 11. List the employees who are eligible for commission.

In [26]:
# MYSQL Query
q("""SELECT * FROM emp WHERE comm IS NOT NULL""")

   empno   ename       job   mgr    hiredate     sal    comm  deptno
0   1234  DHIRAJ   ANALYST  7839  1988-12-17  5000.0   100.0      10
1   7499   ALLEN  SALESMAN  7698  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698  1981-02-22  1250.0   500.0      30
3   7654  MARTIN  SALESMAN  7698  1981-09-28  1250.0  1400.0      30
4   7844  TURNER  SALESMAN  7698  1981-09-08  1500.0     0.0      30

In [27]:
# Equivalent pandas code
result = emp[emp['comm'].notna()]
result

    empno   ename       job     mgr   hiredate     sal    comm  deptno
0    1234  DHIRAJ   ANALYST  7839.0 1988-12-17  5000.0   100.0      10
2    7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
3    7521    WARD  SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
5    7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
10   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500.0     0.0      30

### 12. List employees whose names either start or end with "S".

In [28]:
# MYSQL Query
q("""SELECT ename FROM emp WHERE ename LIKE 'S%' OR ename LIKE '%S'""")

   ename
0  SMITH
1  JONES
2  SCOTT
3  ADAMS
4  JAMES

In [29]:
# Equivalent pandas code
result = emp[emp['ename'].str.startswith('S') | emp['ename'].str.endswith('S')][['ename']]
result

    ename
1   SMITH
4   JONES
8   SCOTT
11  ADAMS
12  JAMES

### 13. List names of employees whose names have "i" as the second character.

In [30]:
# MYSQL Query
q("""SELECT ename FROM emp WHERE ename LIKE '_I%'""")

    ename
0    KING
1  MILLER

In [31]:
# Equivalent pandas code
result = emp[emp['ename'].str[1].str.upper() == 'I'][['ename']]
result

     ename
9     KING
14  MILLER

### 14. List the number of employees working with the company.

In [32]:
# MYSQL Query
q("""SELECT COUNT(*) AS num_employees FROM emp""")

   num_employees
0             15

In [33]:
# Equivalent pandas code
result = pd.DataFrame({'num_employees': [len(emp)]})
result

   num_employees
0             15

### 15. List the number of designations available in the EMP table.

In [34]:
# MYSQL Query
q("""SELECT COUNT(DISTINCT job) AS num_designations FROM emp""")

   num_designations
0                 5

In [35]:
# Equivalent pandas code
result = pd.DataFrame({'num_designations': [emp['job'].nunique()]})
result

   num_designations
0                 5

### 16. List the total salaries paid to the employees.

In [36]:
# MYSQL Query
q("""SELECT SUM(sal) AS total_salary FROM emp""")

   total_salary
0       34025.0

In [37]:
# Equivalent pandas code
result = pd.DataFrame({'total_salary': [emp['sal'].sum()]})
result

   total_salary
0       34025.0

### 17. List the maximum, minimum and average salary in the company.

In [38]:
# MYSQL Query
q("""SELECT MAX(sal) AS max_sal, MIN(sal) AS min_sal, AVG(sal) AS avg_sal FROM emp""")

   max_sal  min_sal      avg_sal
0   5000.0    800.0  2268.333333

In [39]:
# Equivalent pandas code
result = pd.DataFrame({'max_sal': [emp['sal'].max()], 'min_sal': [emp['sal'].min()], 'avg_sal': [emp['sal'].mean()]})
result

   max_sal  min_sal      avg_sal
0   5000.0    800.0  2268.333333

### 18. List the maximum salary paid to a salesman.

In [40]:
# MYSQL Query
q("""SELECT MAX(sal) AS max_salesman_sal FROM emp WHERE job = 'SALESMAN'""")

   max_salesman_sal
0            1600.0

In [41]:
# Equivalent pandas code
result = pd.DataFrame({'max_salesman_sal': [emp[emp['job'] == 'SALESMAN']['sal'].max()]})
result

   max_salesman_sal
0            1600.0

---
## Create queries in mysql and python pandas
All 18 queries above are implemented and executed both ways: as a live MySQL query through the `q()` helper (SQLAlchemy + PyMySQL against the `piit` database), and as an equivalent pandas operation on the `emp` DataFrame loaded from that same database. Both outputs are shown so the two approaches can be cross-checked against each other.